# Generated by Django 4.1.7 on 2023-03-07 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-is_staff'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
